use_frameworks!

target 'RicTaskHelper_Example' do
  pod 'RicTaskHelper', :path => '../'

  target 'RicTaskHelper_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
